name: Build and Push to ACR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: gocloudopsacr
  ACR_SERVER: gocloudopsacr.azurecr.io
  IMAGE_NAME: coderco-task-manager
  IMAGE_TAG: v1
  DOCKERFILE_PATH: ./gocloudops/docker/Dockerfile
  BUILD_CONTEXT: ./gocloudops/

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build -f $DOCKERFILE_PATH -t $ACR_SERVER/$IMAGE_NAME:$IMAGE_TAG $BUILD_CONTEXT

      - name: Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb

      - name: Run Trivy scan
        run: |
          trivy image --severity HIGH,CRITICAL $ACR_SERVER/$IMAGE_NAME:$IMAGE_TAG
        continue-on-error: false

      - name: Push image to ACR
        run: docker push $ACR_SERVER/$IMAGE_NAME:$IMAGE_TAG